### ISSUE TITLE
Question - Environment variables passed to the command

### ISSUE THREAD

**Issue by thim81** [reddec/monexec#11]
Hi Aleksandr,

The `run` support a flag to pass environment variables.

```
-e, --env=ENV ... Environment addition variables
```

Is there an option to load all ENV vars and pass it through the "run" context.
Or an option to load a file with ENV vars?

This will make it easier to use the monexec in automation flows.
Supervisorctl does not support this option, so we always have to load the ENV vars via a work-around.

Regards,
Tim

**Comment by reddec** [comment]
Hi Tim!

No such option right now, however, it's easy to implement. I will do it soon (1-2 days)

Thanks for the idea!

**Comment by reddec** [comment]
Done in v0.1.14
Documentation: https://reddec.github.io/monexec/#environment-variables-from-file
Example of file there or in `sample` directory.

In short: you can use `--env-file` or `-E` multiple times to get environment variables from files

Feel free to open new issue if new ideas or (I hope not) bugs come!
