### ISSUE TITLE
how to run monexec in daemon mod

### ISSUE THREAD

**Issue by li-bit** [reddec/monexec#19]

**Comment by reddec** [comment]
Not sure that I understood question correctly, but pretty sure that supervisor (a service which is running another services) should not be launched in background (daemon mod). Feel free to reopen issue if needed

**Comment by li-bit** [comment]
this situation:
1.monexec run exe
2. i close the ssh

i hope that the monexec  process will not be closed

**Comment by reddec** [comment]
I want you to offer:
A) use a systemd/rc/init.d scripts to run monexec
B) use `nohup` plus `&`
