### ISSUE TITLE
yaml path  bug

### ISSUE THREAD

**Issue by hijk1234** [reddec/monexec#3]
monexec.exe and monexec.yaml in Same directory

C:\Users\Administrator\Desktop\frps>monexec.exe start ./monexec.yaml
2017/10/29 18:02:01 open monexec.yaml/monexec.yaml: The system cannot find the path specified.

C:\Users\Administrator\Desktop\frps>monexec.exe start monexec.yaml
2017/10/29 18:02:57 open monexec.yaml/monexec.yaml: The system cannot find the path specified.

from windows 7 X64

**Comment by reddec** [comment]
Hello!  Just specify only directory : `./` - all `.yaml` or `.yml` will be loaded

For your case:

`C:\Users\Administrator\Desktop\frps>monexec.exe start ./`

**Comment by reddec** [comment]
fixed in 0.1.2
