### ISSUE TITLE
inet_http_server?

### ISSUE THREAD

**Issue by hijk1234** [reddec/monexec#4]
support inet_http_server  ???

like this:
[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; (ip_address:port specifier, *:port for all iface)
username=user              ; (default is no username (open server))
password=123               ; (default is no password (open server))

**Comment by reddec** [comment]
Sounds interesting.
Could you please write details about what do you expect from this server?

**Comment by hijk1234** [comment]
I want to add Web Management
thank you

**Comment by reddec** [comment]
Maybe I can add a simple REST-based endpoint, that will allow you obtain information of current situation of processes. Is that you want?

**Comment by hijk1234** [comment]
I don't quite understand what you mean
My English is so bad

**Comment by hijk1234** [comment]
Based on Web
View running state

**Comment by hijk1234** [comment]
supervisord.conf

; Sample supervisor config file.
;
; For more information on the config file, please see:
; http://supervisord.org/configuration.html
;
; Notes:
;  - Shell expansion ("~" or "$HOME") is not supported.  Environment
;    variables can be expanded using this syntax: "%(ENV_HOME)s".
;  - Comments must have a leading space: "a=b ;comment" not "a=b;comment".

[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)
;chmod=0700                 ; socket file mode (default 0700)
;chown=nobody:nogroup       ; socket file uid:gid owner
;username=user              ; (default is no username (open server))
;password=123               ; (default is no password (open server))

Like this:
[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; (ip_address:port specifier, *:port for all iface)
username=user              ; (default is no username (open server))
password=123               ; (default is no password (open server))


http://X.X.X.X:9001

**Comment by reddec** [comment]
Done in v0.1.7
