### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by hijk1234** [reddec/monexec#5]
/usr/local/config
frps.yaml

services:
- label: frps
  command: /usr/local/frps/frps -c /usr/local/frps/frps.ini
  stop_timeout: 5s
  restart_delay: 2s
  restart: -1

./monexec start /usr/local/config/

[supervisor] 2017/11/14 22:47:58 Runnable frps registered with id bf62b5c8-a387-467f-8a10-5d36fd9d795a
[supervisor] 2017/11/14 22:47:58 Runnable frps spawned with id bf62b5c8-a387-467f-8a10-5d36fd9d795a
[supervisor] 2017/11/14 22:47:58 Runnable frps with id bf62b5c8-a387-467f-8a10-5d36fd9d795a stopped
[supervisor] 2017/11/14 22:47:58 Runnable with id bf62b5c8-a387-467f-8a10-5d36fd9d795a removed
[supervisor] 2017/11/14 22:47:58 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:00 Runnable frps registered with id 1d9ce2a9-ee1c-4e98-b2f6-d8b3294a1487
[supervisor] 2017/11/14 22:48:00 Runnable frps spawned with id 1d9ce2a9-ee1c-4e98-b2f6-d8b3294a1487
[supervisor] 2017/11/14 22:48:00 Runnable frps with id 1d9ce2a9-ee1c-4e98-b2f6-d8b3294a1487 stopped
[supervisor] 2017/11/14 22:48:00 Runnable with id 1d9ce2a9-ee1c-4e98-b2f6-d8b3294a1487 removed
[supervisor] 2017/11/14 22:48:00 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:02 Runnable frps registered with id da843b11-6fb1-46d3-abeb-d1d08d32ab41
[supervisor] 2017/11/14 22:48:02 Runnable frps spawned with id da843b11-6fb1-46d3-abeb-d1d08d32ab41
[supervisor] 2017/11/14 22:48:02 Runnable frps with id da843b11-6fb1-46d3-abeb-d1d08d32ab41 stopped
[supervisor] 2017/11/14 22:48:02 Runnable with id da843b11-6fb1-46d3-abeb-d1d08d32ab41 removed
[supervisor] 2017/11/14 22:48:02 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:04 Runnable frps registered with id b3c7fff1-ae5c-4765-b740-372527ce8788
[supervisor] 2017/11/14 22:48:04 Runnable frps spawned with id b3c7fff1-ae5c-4765-b740-372527ce8788
[supervisor] 2017/11/14 22:48:04 Runnable frps with id b3c7fff1-ae5c-4765-b740-372527ce8788 stopped
[supervisor] 2017/11/14 22:48:04 Runnable with id b3c7fff1-ae5c-4765-b740-372527ce8788 removed
[supervisor] 2017/11/14 22:48:04 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:06 Runnable frps registered with id 44e316aa-c041-4284-ac99-e3f779f17866
[supervisor] 2017/11/14 22:48:06 Runnable frps spawned with id 44e316aa-c041-4284-ac99-e3f779f17866
[supervisor] 2017/11/14 22:48:06 Runnable frps with id 44e316aa-c041-4284-ac99-e3f779f17866 stopped
[supervisor] 2017/11/14 22:48:06 Runnable with id 44e316aa-c041-4284-ac99-e3f779f17866 removed
[supervisor] 2017/11/14 22:48:06 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:08 Runnable frps registered with id 06c8a422-ae42-4154-af1d-1c1eda17ddc3
[supervisor] 2017/11/14 22:48:08 Runnable frps spawned with id 06c8a422-ae42-4154-af1d-1c1eda17ddc3
[supervisor] 2017/11/14 22:48:08 Runnable frps with id 06c8a422-ae42-4154-af1d-1c1eda17ddc3 stopped
[supervisor] 2017/11/14 22:48:08 Runnable with id 06c8a422-ae42-4154-af1d-1c1eda17ddc3 removed
[supervisor] 2017/11/14 22:48:08 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:10 Runnable frps registered with id a46c16a2-944b-4fe3-aa0f-d5471c4803c8
[supervisor] 2017/11/14 22:48:10 Runnable frps spawned with id a46c16a2-944b-4fe3-aa0f-d5471c4803c8
[supervisor] 2017/11/14 22:48:10 Runnable frps with id a46c16a2-944b-4fe3-aa0f-d5471c4803c8 stopped
[supervisor] 2017/11/14 22:48:10 Runnable with id a46c16a2-944b-4fe3-aa0f-d5471c4803c8 removed
[supervisor] 2017/11/14 22:48:10 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:12 Runnable frps registered with id c7df8753-2cab-4675-8c79-afcbf058b16b
[supervisor] 2017/11/14 22:48:12 Runnable frps spawned with id c7df8753-2cab-4675-8c79-afcbf058b16b
[supervisor] 2017/11/14 22:48:12 Runnable frps with id c7df8753-2cab-4675-8c79-afcbf058b16b stopped
[supervisor] 2017/11/14 22:48:12 Runnable with id c7df8753-2cab-4675-8c79-afcbf058b16b removed
[supervisor] 2017/11/14 22:48:12 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:14 Runnable frps registered with id 647aad21-63b7-410d-98e4-b75a54e70d1d
[supervisor] 2017/11/14 22:48:14 Runnable frps spawned with id 647aad21-63b7-410d-98e4-b75a54e70d1d
[supervisor] 2017/11/14 22:48:14 Runnable frps with id 647aad21-63b7-410d-98e4-b75a54e70d1d stopped
[supervisor] 2017/11/14 22:48:14 Runnable with id 647aad21-63b7-410d-98e4-b75a54e70d1d removed
[supervisor] 2017/11/14 22:48:14 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:16 Runnable frps registered with id 6bfa8904-48c5-4363-a8ec-5b3b8f8efdfb
[supervisor] 2017/11/14 22:48:16 Runnable frps spawned with id 6bfa8904-48c5-4363-a8ec-5b3b8f8efdfb
[supervisor] 2017/11/14 22:48:16 Runnable frps with id 6bfa8904-48c5-4363-a8ec-5b3b8f8efdfb stopped
[supervisor] 2017/11/14 22:48:16 Runnable with id 6bfa8904-48c5-4363-a8ec-5b3b8f8efdfb removed
[supervisor] 2017/11/14 22:48:16 Monitor will respawn frps after 2s
[supervisor] 2017/11/14 22:48:18 Runnable frps registered with id 8c198707-da1a-45cb-8261-a723e2a1a807
[supervisor] 2017/11/14 22:48:18 Runnable frps spawned with id 8c198707-da1a-45cb-8261-a723e2a1a807
[supervisor] 2017/11/14 22:48:18 Runnable frps with id 8c198707-da1a-45cb-8261-a723e2a1a807 stopped
[supervisor] 2017/11/14 22:48:18 Runnable with id 8c198707-da1a-45cb-8261-a723e2a1a807 removed
[supervisor] 2017/11/14 22:48:18 Monitor will respawn frps after 2s

**Comment by reddec** [comment]
Ok.
From logs it's looks like all OK. Just `frps` crashes instantly. Not sure, that this is a problem of monexec

**Comment by hijk1234** [comment]
command    after
support specify a path?   command: /usr/local/frps/frps -c /usr/local/frps/frps.ini

**Comment by reddec** [comment]
Try use generator:

`monexec run --generate -- /usr/local/frps/frps -c /usr/local/frps/frps.ini`

and then check that generated YAML is same as your

**Comment by hijk1234** [comment]
I've tried it already
nonsupport
Hope to be able to repair

https://github.com/fatedier/frp

**Comment by reddec** [comment]
Please show me log after this config
```yaml
- label: frps-test
  command: /usr/local/frps/frps
  args:
  - -c
  - /usr/local/frps/frps.ini
  stop_timeout: 5s
  restart_delay: 5s
  restart: -1
```

**Comment by hijk1234** [comment]
success, Thank you

But how do you add it to the system service?

monexec.service

[Unit]
Description=monexec
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/monexec start /usr/local/config/
ExecStop=/usr/local/monexec $OPTIONS shutdown
ExecReload=/usr/local/monexec $OPTIONS reload
KillMode=process
Restart=on-failure
RestartSec=42s

[Install]
WantedBy=multi-user.target


Tested,But it failed

centos7 x64

**Comment by reddec** [comment]
There are not shutdown or reload functions.
Just use

```
[Unit]
Description=monexec
After=network.target

[Service]
ExecStart=/usr/local/monexec start /usr/local/config/
Restart=on-failure
RestartSec=42s

[Install]
WantedBy=multi-user.target
```

That wil be enough. Anything else Systemd will do automatically.
If problem will persist, use `journalctl -xe` or `journalctl -u monexec` to inspect problems

**Comment by hijk1234** [comment]
Thank you very much. It has been successful

**Comment by hijk1234** [comment]
I don't quite understand what you mean
My English is so bad
