### ISSUE TITLE
how can it run the project in backgroud?

### ISSUE THREAD

**Issue by u5de6** [reddec/monexec#6]
what‘s the different between use command 'go run' and 'monexec'(not use consul), if i want to run the project in backgroud, how can i do?
maybe use supervisor is more better for the moment

**Comment by reddec** [comment]
Best answer will be another question: will `go run` restart your application on fail? With delay, notifications and everything else? Can it run multiple applications?

About supervisord: monexec inspired from ideas of that project, but there are some benefits:

* one executable only: no deployment - copy-and-run only
* minimal disk overhead: python + modules much more than just one monexec. very important for containers and bare systems
* less memory and CPU overhead - can't say that it's critical right now, but anyway
* monexec - tool with 'batteries included': all notifications, restart policy and else you can do by multiple other instruments with orchestration. It's like docker - everyone can use raw LXC/LXD or whatever, but it would be much easier to just use Docker
* easy to extend

**Comment by u5de6** [comment]
thanks for your explanations, yeah, it's lighter and more convenient. i just started using the monexec, perhaps i haven't used it correctly. 
because i deployed the project in kubernetes, so i can crontrol easier by kubelet, like restart policy, monitor.
But if i want to manage the project in the local and run in the backgroud, use monexec,  is there a better way to adopt? Can you give me some suggestions, i adopt the way used supervisor for the moment.

**Comment by reddec** [comment]
You are welcome!
Personally, I am using SystemD service file or tmux (+ CTRL-B + D for detach) during debugging
