### ISSUE TITLE
how can i stop a specified service

### ISSUE THREAD

**Issue by sjatsh** [reddec/monexec#7]
how can i stop a specified service?
can  you add instructions?

**Comment by reddec** [comment]
good day! 
monexec originally was not designed for control each process separatly.

The application can:

* stop every other process if one of them failed (it's called 'critical' process)
* stop everything by signal with timeout (graceful shutdown or force terminating stucked processes)

The application **can not**:

* start application application that was not defined in config
* stop only specific applications (except situation the described below)

Temporary workaround: you can kill process by signal (OS specific, but usually something like `kill -<signum> <pid>`) and then if no `critical` processes defined and restart retries is limited to zero then only the one process stopped.

But in any case this is quite popular question. I think I will add some way to start/stop processes 'on fly'

**Comment by reddec** [comment]
Since v0.1.6 (80140db) you can do it by REST API: 

* stop single service: 

```bash
curl -X POST "http://localhost:9900/instance/NAME"
```

* spawn service again:  

```bash
curl -X POST "http://localhost:9900/supervisor/NAME"`
```

where `NAME` - must be name of your service.

Of course REST plugin must be enabled. Ex:

```yaml
rest:
  listen: "localhost:9900"
```
